### ISSUE TITLE
Best settings for light weight/size images

### ISSUE THREAD

**Issue by blogdemoi** [makew0rld/didder#10]
Hi,

I plan to use didder to convert images in my blog to gain speed thus reducing image weight/size. What would be the best settings/options to use in didder, keeping colors or black and white?

Thank you.

**Comment by makew0rld** [comment]
Either colors or grayscale is fine, but it is likely more about palette size. If you only use two colors, for example, then only one bit needs to be stored per pixel.

As for specific options, the best advice I have is all contained the manpage: https://github.com/makeworld-the-better-one/didder/blob/main/MANPAGE.md

Good luck, feel free to send me a link to your blog once it's up and running!
