### ISSUE TITLE
Edm command doesn't work

### ISSUE THREAD

**Issue by piegit** [makew0rld/didder#12]
Command i'm using is
`didder -i david.png -o david_dithered.png --palette "black white" --recolor "black F273FF" --upscale 2 edm Sierra2`

and I get `couldn't process argument as matrix name, inline JSON, or path to accessible JSON file`

OS: Windows 10 Home 
Architecture: x86-64

**Comment by makew0rld** [comment]
I see you've closed this. Let me know if you're still having an issue.
