### ISSUE TITLE
--seed and --serpentine no work

### ISSUE THREAD

**Issue by ETO-QSH** [makew0rld/didder#22]
I see the --seed and --serpentine parameters in readme, but when I use releases, if I put them in front of the algorithm, the prompt "flag provided but not defined: -seed ", which if placed after the algorithm tells me that the number of arguments is incorrect. Please tell me how to deal with these two parameters.

**Comment by makew0rld** [comment]
`--seed` can only be used with the `random` subcommand, and `--serpentine` can only be used with the `edm` subcommand. For more details see the [manual](https://github.com/makew0rld/didder/blob/main/MANPAGE.md). If you are still having issues, please paste the full command you are running that doesn't work.

**Comment by ETO-QSH** [comment]
I tested these but they all had problems (leaving out most of the colors on the palette). I have read the manual you mentioned and there is no gain (or gain from knowing the two possible parameters --seed and --serpentine).Please tell me how to write the commands about --seed and --serpentine correctly.


**random**

① didder.exe --in input_image.png --out output_image.png  --strength 100% --palette "#597D27 #6D9930 #43584F"  --seed 123123 random -0.5,0.5 -0.5,0.5 -0.5,0.5 

Incorrect Usage. flag provided but not defined: -seed
... ... ... Omit the help documents ... ... ...
flag provided but not defined: -seed

② didder.exe --in input_image.png --out output_image.png  --strength 100% --palette "#597D27 #6D9930 #43584F" random -0.5,0.5 -0.5,0.5 -0.5,0.5 --seed 123123

random needs 2 or 6 arguments


**edm**

① didder.exe --in input_image.png --out output_image.png  --strength 100% --palette "#597D27 #6D9930 #43584F" --serpentine edm FalseFloydSteinberg

Incorrect Usage. flag provided but not defined: -serpentine
... ... ... Omit the help documents ... ... ...
flag provided but not defined: -serpentine

② didder.exe --in input_image.png --out output_image.png  --strength 100% --palette "#597D27 #6D9930 #43584F" edm FalseFloydSteinberg --serpentine

edm only accepts one argument

**Comment by makew0rld** [comment]
The subcommand flags need to be immediately after the subcommand name. For example:

```
$ didder.exe --in input_image.png --out output_image.png --strength 100% --palette "#597D27 #6D9930 #43584F" random --seed 123123 -0.5,0.5 -0.5,0.5 -0.5,0.5
$ didder.exe --in input_image.png --out output_image.png --strength 100% --palette "#597D27 #6D9930 #43584F" edm --serpentine FalseFloydSteinberg
```

Let me know if that fixes your issue.

**Comment by ETO-QSH** [comment]
This was very successful, thanks for your help (maybe you should add such examples with documentation, no instructions put in this position, I see such cold 'random needs 2 or 6 arguments' QWQ)
