### ISSUE TITLE
Convert 24-bit PNG to 8-bit PNG

### ISSUE THREAD

**Issue by sergeevabc** [makew0rld/didder#6]
Dear @makeworld,
how do I reduce 24-bit png to 8-bit 256-colors palette png by means of `didder`?

**Comment by makew0rld** [comment]
You would have to specify all 256 colors in the `--palette` argument, as those are the colors you want in your output. However this would be gigantic and would exceed the character limit for command-line options. So it is not possible with this tool.

This tool is intended for much more limited palettes, not general PNG conversion. ImageMagick should be able to do what you're looking for.
