### ISSUE TITLE
Possible corrupt gif generated

### ISSUE THREAD

**Issue by mntn-xyz** [makew0rld/didder#7]
via https://github.com/skyjake/lagrange/issues/353

I generated a GIF with the following didder options: `-f gif -x 600 -p 'tomato orange gold lightseagreen cornflowerblue mediumpurple black ivory' edm --serpentine Simple2D`. This image won't display properly in Lagrange. Apparently running GraphicsMagick on the image fixed it (per the linked discussion) but this process adds 48 bytes.

Strangely I am able to view the image just fine in a couple of other programs. Maybe they are more forgiving than std_image (used by Langrange), or it is possible that the generated image uses a format that is technically valid but is not widely supported. The fact that GraphicsMagick adds bytes and this "fixes" it makes me think that something important is missing from the image data.

I've attached the two example images.

Original:
![test](https://user-images.githubusercontent.com/85877297/136243875-a7572e01-2b0a-4db9-8350-69da58a9c0d3.gif)

Fixed:
![test-fixed](https://user-images.githubusercontent.com/85877297/136243870-ea9638c0-07c2-40d2-adff-f1a8e494d614.gif)

**Comment by mntn-xyz** [comment]
Oh, and the original source image: https://mntn.xyz/test-markdown-syntax/PIXNIO-2545657-5760x3840.jpeg

**Comment by makew0rld** [comment]
Happy to hear someone's using this application!

I'm not doing anything strange with the GIFs, just using Go's standard library GIF encoder. When I look through Go's issues, it does seem like other people are having problems with GIFs, but the conclusion always seems to be poor coding on the viewer's end. So that's what I suspect here, that whatever Go's doing is within the spec, just not expected by some viewers.

See these issues: https://github.com/golang/go/issues/33748 | https://github.com/golang/go/issues/13746 | https://github.com/golang/go/issues/26108

I am pretty curious as to what GraphicsMagick is adding, let me know if you're able to figure it out. It'll probably require some binary diffing tools, a good understanding of the GIF spec, and maybe decompressing the GIF file. Unless the issue is with the compression itself.

To solve your specific issue here, I'd either switch to PNG, which probably has smaller file sizes anyway, or run all your images through GraphicsMagick before uploading. Sorry!

P.S. what gemini capsule are you putting these on? Would love to check it out!

**Comment by makew0rld** [comment]
Also I would suggest opening a bug for stb_image about this. And whatever library Ariane is using.

**Comment by mntn-xyz** [comment]
Thanks, will take a look at the Go issues and investigate that as a possibility. (Capsule is hosted at gemini://mntn.xyz by the way.)

For what it's worth, looking at the hexdump of the two images, the original image is missing information from its packed field in the Logical Screen Descriptor. The color resolution bits from the original image are 000. These bits represent the "number of bits per primary color available to the original image, minus 1," so 000 is obviously incorrect... it should indicate 3 bits at least, although the "fixed" image indicates a full 8 bits after processing through GraphicsMagick. https://www.matthewflickinger.com/lab/whatsinagif/bits_and_bytes.asp

For reference, here's the Go code that writes the header. I'm looking into it more now. https://cs.opensource.google/go/go/+/refs/tags/go1.17.1:src/image/gif/writer.go;drc=refs%2Ftags%2Fgo1.17.1;l=144

**Comment by mntn-xyz** [comment]
Interesting, it looks like the code should be properly determining the length of the color palette and writing the bytes... but for this image it was not. See https://cs.opensource.google/go/go/+/refs/tags/go1.17.1:src/image/gif/writer.go;l=158;drc=refs%2Ftags%2Fgo1.17.1

**Comment by makew0rld** [comment]
Thanks for taking a look into this. Fingers crossed we can get this fixed for everyone! Let me know what else you find from looking into the code, and let me know if you need any help if you don't have Go experience. I'd like to look into this as well sometime soon.

Also, did you build the binaries yourself or download from the releases page? Because the GitHub binaries were built with Go 1.16, not 1.17. So it might be worthwhile to look at that code if you used those binaries, and compare to 1.17 if you find any issue.

**Comment by mntn-xyz** [comment]
Thanks, I will take a deeper look in a bit. I need to trace how the palette info gets from point A in didder to point B in the image library code linked above. I'm fairly new to Go, but it hasn't been hard to pick up, and I think I can get it figured out.

I built the binaries from a Nix expression, which should be using 1.16.8. I'll probably end up packaging didder for Nix at some point, it would be a useful tool to have. Also, I wrote a script that people can use to dither their whole Gemini site (and update image links), which is how I found this issue in the first place! https://git.sr.ht/~mntn/gemdither

**Comment by makew0rld** [comment]
Oh well I can definitely help with any didder code stuff, just let me know what your question is.

> I built the binaries from a Nix expression, which should be using 1.16.8.

Ok nice, I'd stick to code from that tag then. Likely the issue still exists, but good to be sure.

> I'll probably end up packaging didder for Nix at some point

That'd be awesome, thanks! And that script is super cool! Makes me happy to see didder put to good use.

**Comment by mntn-xyz** [comment]
It's definitely not an issue with didder, same behavior is present in the dither library. I'll close this, will reopen there if it turns out to be an issue with dither.

**Comment by makew0rld** [comment]
Ok, thanks. Feel free to put some updates in this thread though, this is interesting.

**Comment by mntn-xyz** [comment]
Also just verified that using the Go image library directly produces the same issue. I'll file a bug with both stb (which should probably be more tolerant) and Go (which should produce valid images).

**Comment by makew0rld** [comment]
Sounds good! Maybe whatever library Ariane is using as well. Please link the Go GitHub issue here.

**Comment by mntn-xyz** [comment]
Ariane seems to have a lot of problems with their image processing, I see some issues on their tracker that seem to indicate a rewrite is underway. So I'll avoid piling on for now :)

**Comment by nothings** [comment]
Author of stb_image. <s>As far as I understand it, having a 0 in the specified byte relies on using features of the animated GIF spec, which stb_image does not support. Apparently the Go GIF package does this if you don't supply a global palette, but I'm not 100% sure how this maps to the input options in the API: https://cs.opensource.google/go/go/+/refs/tags/go1.17.1:src/image/gif/writer.go;l=172

<pre>
if p, ok := e.g.Config.ColorModel.(color.Palette); ok && len(p) > 0 {
	paddedSize := log2(len(p)) // Size of Global Color Table: 2^(1+n).
	<b>e.buf[0] = fColorTable | uint8(paddedSize)</b>
	e.buf[1] = e.g.BackgroundIndex
	e.buf[2] = 0x00 // Pixel Aspect Ratio.
	e.write(e.buf[:3])
	var err error
	e.globalCT, err = encodeColorTable(e.globalColorTable[:], p, paddedSize)
	if err != nil && e.err == nil {
		e.err = err
		return
	}
	e.write(e.globalColorTable[:e.globalCT])
} else {
	// All frames have a local color table, so a global color table
	// is not needed.
	<b>e.buf[0] = 0x00</b>
	e.buf[1] = 0x00 // Background Color Index.
	e.buf[2] = 0x00 // Pixel Aspect Ratio.
	e.write(e.buf[:3])
}
</pre>
</s>

**Comment by nothings** [comment]
Correction: there IS code in stb_image to handle the specific issue noted above, I think (it supports both global and local color tables), even though there's no animated GIF support, so I'd have to investigate more to find out why it doesn't work (hopefully this weekend). Presumably it's not that 0 byte that causes the problem, but something later in the file. Is it possibly actually being encoded as an animated GIF (which would definitely break)?

**Comment by mntn-xyz** [comment]
I'm not entirely clear, as far as I can tell from looking at Go's Encode() then it does seem to be populating the global color info, which should then be written per the code you pasted above. Of course there could be a hard-to-spot error in all of it.

The simplest way to create a broken image:
```
img := image.NewRGBA(image.Rect(0, 0, 12, 6))
opts := gif.Options{
  NumColors: 2,
}
out, err := os.Create("broken.gif")
gif.Encode(out, img, &opts)
out.Close()
```

Image generated:
![broken](https://user-images.githubusercontent.com/85877297/136438720-300d9d83-f366-4aec-aa5c-21fe5f13ba1d.gif)

Image hex:
```
00000000: 4749 4638 3961 0c00 0600 8000 0000 0000  GIF89a..........
00000010: 0000 442c 0000 0000 0c00 0600 0002 07f0  ..D,............
00000020: 3175 b9fd 5501 003b                      1u..U..;
```

**Comment by nothings** [comment]
Ok, I used the error message from stb_image to find out what the actual issue is. This makes sense as an error in Go GIF that would only trip some decoders, causing random issues through the years.

https://github.com/nothings/stb/issues/1222#issuecomment-938027720

**Comment by mntn-xyz** [comment]
Thanks, yeah it looks like the GIFs generated by Go have a few issues. I'll see if I can dig into the Go code when I have a chance. This turned into a wild goose chase...

**Comment by nothings** [comment]
FWIW I don't think the Go GIF issues linked earlier in the thread ( https://github.com/makeworld-the-better-one/didder/issues/7#issuecomment-936666381 ) are related.

**Comment by mntn-xyz** [comment]
I think they might actually be related since the first two seem to be LZW issues. I looked in detail at the bytes and you're right, it's a missing clear code. Most sources seem to say that this code is mandatory (although the W3C spec does not), so they should be outputting the code especially since legacy code may require it. It's not like the extra byte or two is going to hurt anybody.

**Comment by nothings** [comment]
AFAICT the W3C spec is just a copy of the GIF89a specification and contains the exact same "Encoders should output a Clear code as the first code of each image data stream" line which is intended to make it mandatory.

**Comment by mntn-xyz** [comment]
You might want to weigh in on https://github.com/golang/go/issues/33748; your take as a library author may help inform the Go team's prioritization. It looks like they moved this to backlog in 2019, probably because nobody could identify exactly what the issue was.

**Comment by nothings** [comment]
It may need a new bug report, as the project the original bug is about appears to have rewritten their lzw decoder in 2019 and may have have dropped the 'require initial clear code' requirement.

But I have literally 0 desire to try spend any time trying to convince anyone on the Go team specifically that "should" means "MUST". I intentionally wrote the comment in the stb_image repository so someone else can cite it without me getting involved.

**Comment by makew0rld** [comment]
@mntn-xyz thanks for making comments and explaining in golang/go#33748. We'll see if Go devs respond, and if not maybe making a new bug report is a good idea as @nothings suggests.

> But I have literally 0 desire to try spend any time trying to convince anyone on the Go team specifically that "should" means "MUST". I intentionally wrote the comment in the stb_image repository so someone else can cite it without me getting involved.

No worries, thanks for making that comment and looking into things. I think either mntn or I would be happy to take things further.

**Comment by mntn-xyz** [comment]
I'll file a new bug if nobody notices my comments, but I want to give it a bit so I'm not spamming their bug tracker re: this issue.

**Comment by mntn-xyz** [comment]
Update for anyone else reading this thread, Go devs have acknowledged the issue and a patch is in progress: https://go-review.googlesource.com/c/go/+/354710/
